---
  - name: Install mongodb
    apt:
      name: mongodb
      state: present
    tags: install

  - name: Enable mongodb service
    service:
      name: mongodb
      enabled: true
    tags: install
