- name: Add unit file for puma
  template:
    src: reddit.service.j2
    dest: /etc/systemd/system/reddit.service
  notify: reload reddit

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: "/home/{{ deploy_user }}/db_config"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

- name: enable puma
  systemd:
    name: reddit
    enabled: yes
