---
- name: Install soft for db
  hosts: all
  become: true

  tasks:
  - name: Install mongodb
    ansible.builtin.apt:
      name: mongodb
      state: present

  - name: Enable mongodb service
    service:
      name: mongodb
      enabled: true
