---
- name: Configure db host
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0

  tasks:
  - name: Change mongo config file
    template:
      src: templates/mongod.conf.j2
      dest: /etc/mongodb.conf
      mode: 0644
    notify: restart mongod


  handlers:
  - name: restart mongod
    service: name=mongodb state=restarted

- name: Configure app host
  hosts: app
  tags: app-tag
  become: true
  vars:
    db_host: 10.128.0.15

  tasks:
  - name: Add unit file for puma
    copy:
      src: files/reddit.service
      dest: /etc/systemd/system/reddit.service
    notify: reload reddit

  - name: Add config for DB connection
    template:
      src: templates/db_config.j2
      dest: /home/ubuntu/db_config
      owner: ubuntu
      group: ubuntu

  - name: enable puma
    systemd: name=reddit enabled=yes

  handlers:
  - name: reload reddit
    systemd: name=reddit state=restarted

- name: Deploy application
  hosts: app
  tags: deploy-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 10.128.0.22

  tasks:
  - name: install git
    apt:
      name: git
      state: present

  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/ubuntu/reddit
      version: monolith
    notify: reload reddit

  - name: Bundle install
    bundler:
      state: present
      chdir: /home/ubuntu/reddit

  handlers:
  - name: reload reddit
    systemd: name=reddit state=restarted
